package com.p2082ss.android.ugc.aweme.feed.model;

import com.bytedance.covode.number.Covode;
import com.google.gson.p2018a.AbstractC27891c;
import java.io.Serializable;
import p4600h.p4611f.p4613b.C89219l;

/* renamed from: com.ss.android.ugc.aweme.feed.model.CaptionItemModel */
public final class CaptionItemModel implements Serializable {
    @AbstractC27891c(mo46611a = "cla_subtitle_id")
    public String claSubtitleId;
    @AbstractC27891c(mo46611a = "complaint_id")
    public long complaintId;
    @AbstractC27891c(mo46611a = "expire")
    public long expire;
    @AbstractC27891c(mo46611a = "caption_format")
    public String format;
    @AbstractC27891c(mo46611a = "is_auto_generated")
    public boolean isAutoGenerated;
    @AbstractC27891c(mo46611a = "language_id")
    public long languageId;
    @AbstractC27891c(mo46611a = "lang")
    public String languageName;
    @AbstractC27891c(mo46611a = "sub_id")
    public int subId;
    @AbstractC27891c(mo46611a = "translator_id")
    public String translatorId;
    @AbstractC27891c(mo46611a = "url")
    public String url;
    @AbstractC27891c(mo46611a = "sub_version")
    public String versionType;

    static {
        Covode.recordClassIndex(58661);
    }

    public CaptionItemModel() {
        this(null, 0, null, 0, null, 0, false, 0, null, null, null, 2047, null);
    }

    /* renamed from: com_ss_android_ugc_aweme_feed_model_CaptionItemModel_com_ss_android_ugc_aweme_lancet_HashCodeLancet_hashCode */
    public static int m93171xe77e6088(int i) {
        return i;
    }

    /* renamed from: com_ss_android_ugc_aweme_feed_model_CaptionItemModel_com_ss_android_ugc_aweme_lancet_HashCodeLancet_hashCode */
    public static int m93172xe77e6088(long j) {
        return (int) (j ^ (j >>> 32));
    }

    public static /* synthetic */ CaptionItemModel copy$default(CaptionItemModel captionItemModel, String str, long j, String str2, long j2, String str3, long j3, boolean z, int i, String str4, String str5, String str6, int i2, Object obj) {
        boolean z2 = z;
        int i3 = i;
        String str7 = str4;
        String str8 = str5;
        String str9 = str6;
        if ((i2 & 1) != 0) {
            str = captionItemModel.languageName;
        }
        if ((i2 & 2) != 0) {
            j = captionItemModel.languageId;
        }
        if ((i2 & 4) != 0) {
            str2 = captionItemModel.url;
        }
        if ((i2 & 8) != 0) {
            j2 = captionItemModel.expire;
        }
        if ((i2 & 16) != 0) {
            str3 = captionItemModel.format;
        }
        if ((i2 & 32) != 0) {
            j3 = captionItemModel.complaintId;
        }
        if ((i2 & 64) != 0) {
            z2 = captionItemModel.isAutoGenerated;
        }
        if ((i2 & 128) != 0) {
            i3 = captionItemModel.subId;
        }
        if ((i2 & 256) != 0) {
            str7 = captionItemModel.versionType;
        }
        if ((i2 & 512) != 0) {
            str8 = captionItemModel.claSubtitleId;
        }
        if ((i2 & 1024) != 0) {
            str9 = captionItemModel.translatorId;
        }
        return captionItemModel.copy(str, j, str2, j2, str3, j3, z2, i3, str7, str8, str9);
    }

    public final String component1() {
        return this.languageName;
    }

    public final String component10() {
        return this.claSubtitleId;
    }

    public final String component11() {
        return this.translatorId;
    }

    public final long component2() {
        return this.languageId;
    }

    public final String component3() {
        return this.url;
    }

    public final long component4() {
        return this.expire;
    }

    public final String component5() {
        return this.format;
    }

    public final long component6() {
        return this.complaintId;
    }

    public final boolean component7() {
        return this.isAutoGenerated;
    }

    public final int component8() {
        return this.subId;
    }

    public final String component9() {
        return this.versionType;
    }

    public final CaptionItemModel copy(String str, long j, String str2, long j2, String str3, long j3, boolean z, int i, String str4, String str5, String str6) {
        C89219l.m154721d(str, "");
        C89219l.m154721d(str2, "");
        C89219l.m154721d(str3, "");
        C89219l.m154721d(str4, "");
        C89219l.m154721d(str5, "");
        C89219l.m154721d(str6, "");
        return new CaptionItemModel(str, j, str2, j2, str3, j3, z, i, str4, str5, str6);
    }

    public final boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof CaptionItemModel)) {
            return false;
        }
        CaptionItemModel captionItemModel = (CaptionItemModel) obj;
        return C89219l.m154714a(this.languageName, captionItemModel.languageName) && this.languageId == captionItemModel.languageId && C89219l.m154714a(this.url, captionItemModel.url) && this.expire == captionItemModel.expire && C89219l.m154714a(this.format, captionItemModel.format) && this.complaintId == captionItemModel.complaintId && this.isAutoGenerated == captionItemModel.isAutoGenerated && this.subId == captionItemModel.subId && C89219l.m154714a(this.versionType, captionItemModel.versionType) && C89219l.m154714a(this.claSubtitleId, captionItemModel.claSubtitleId) && C89219l.m154714a(this.translatorId, captionItemModel.translatorId);
    }

    public final int hashCode() {
        String str = this.languageName;
        int i = 0;
        int hashCode = (((str != null ? str.hashCode() : 0) * 31) + m93172xe77e6088(this.languageId)) * 31;
        String str2 = this.url;
        int hashCode2 = (((hashCode + (str2 != null ? str2.hashCode() : 0)) * 31) + m93172xe77e6088(this.expire)) * 31;
        String str3 = this.format;
        int hashCode3 = (((hashCode2 + (str3 != null ? str3.hashCode() : 0)) * 31) + m93172xe77e6088(this.complaintId)) * 31;
        boolean z = this.isAutoGenerated;
        if (z) {
            z = true;
        }
        int i2 = z ? 1 : 0;
        int i3 = z ? 1 : 0;
        int i4 = z ? 1 : 0;
        int com_ss_android_ugc_aweme_feed_model_CaptionItemModel_com_ss_android_ugc_aweme_lancet_HashCodeLancet_hashCode = (((hashCode3 + i2) * 31) + m93171xe77e6088(this.subId)) * 31;
        String str4 = this.versionType;
        int hashCode4 = (com_ss_android_ugc_aweme_feed_model_CaptionItemModel_com_ss_android_ugc_aweme_lancet_HashCodeLancet_hashCode + (str4 != null ? str4.hashCode() : 0)) * 31;
        String str5 = this.claSubtitleId;
        int hashCode5 = (hashCode4 + (str5 != null ? str5.hashCode() : 0)) * 31;
        String str6 = this.translatorId;
        if (str6 != null) {
            i = str6.hashCode();
        }
        return hashCode5 + i;
    }

    public final String toString() {
        return "CaptionItemModel(languageName=" + this.languageName + ", languageId=" + this.languageId + ", url=" + this.url + ", expire=" + this.expire + ", format=" + this.format + ", complaintId=" + this.complaintId + ", isAutoGenerated=" + this.isAutoGenerated + ", subId=" + this.subId + ", versionType=" + this.versionType + ", claSubtitleId=" + this.claSubtitleId + ", translatorId=" + this.translatorId + ")";
    }

    public final String getClaSubtitleId() {
        return this.claSubtitleId;
    }

    public final long getComplaintId() {
        return this.complaintId;
    }

    public final long getExpire() {
        return this.expire;
    }

    public final String getFormat() {
        return this.format;
    }

    public final long getLanguageId() {
        return this.languageId;
    }

    public final String getLanguageName() {
        return this.languageName;
    }

    public final int getSubId() {
        return this.subId;
    }

    public final String getTranslatorId() {
        return this.translatorId;
    }

    public final String getUrl() {
        return this.url;
    }

    public final String getVersionType() {
        return this.versionType;
    }

    public final boolean isAutoGenerated() {
        return this.isAutoGenerated;
    }

    public CaptionItemModel(String str, long j, String str2, long j2, String str3, long j3, boolean z, int i, String str4, String str5, String str6) {
        C89219l.m154721d(str, "");
        C89219l.m154721d(str2, "");
        C89219l.m154721d(str3, "");
        C89219l.m154721d(str4, "");
        C89219l.m154721d(str5, "");
        C89219l.m154721d(str6, "");
        this.languageName = str;
        this.languageId = j;
        this.url = str2;
        this.expire = j2;
        this.format = str3;
        this.complaintId = j3;
        this.isAutoGenerated = z;
        this.subId = i;
        this.versionType = str4;
        this.claSubtitleId = str5;
        this.translatorId = str6;
    }

    /* JADX WARNING: Illegal instructions before constructor call */
    /* Code decompiled incorrectly, please refer to instructions dump. */
    public /* synthetic */ CaptionItemModel(java.lang.String r17, long r18, java.lang.String r20, long r21, java.lang.String r23, long r24, boolean r26, int r27, java.lang.String r28, java.lang.String r29, java.lang.String r30, int r31, p4600h.p4611f.p4613b.C89214g r32) {
        /*
            r16 = this;
            r14 = r29
            r13 = r28
            r1 = r31
            r12 = r27
            r8 = r23
            r2 = r17
            r11 = r26
            r3 = r18
            r6 = r21
            r5 = r20
            r0 = r1 & 1
            java.lang.String r15 = ""
            if (r0 == 0) goto L_0x001b
            r2 = r15
        L_0x001b:
            r0 = r1 & 2
            r9 = 0
            if (r0 == 0) goto L_0x0023
            r3 = 0
        L_0x0023:
            r0 = r1 & 4
            if (r0 == 0) goto L_0x0028
            r5 = r15
        L_0x0028:
            r0 = r1 & 8
            if (r0 == 0) goto L_0x002e
            r6 = 0
        L_0x002e:
            r0 = r1 & 16
            if (r0 == 0) goto L_0x0033
            r8 = r15
        L_0x0033:
            r0 = r1 & 32
            if (r0 == 0) goto L_0x0058
        L_0x0037:
            r0 = r1 & 64
            if (r0 == 0) goto L_0x003c
            r11 = 1
        L_0x003c:
            r0 = r1 & 128(0x80, float:1.794E-43)
            if (r0 == 0) goto L_0x0041
            r12 = 0
        L_0x0041:
            r0 = r1 & 256(0x100, float:3.59E-43)
            if (r0 == 0) goto L_0x0046
            r13 = r15
        L_0x0046:
            r0 = r1 & 512(0x200, float:7.175E-43)
            if (r0 == 0) goto L_0x004b
            r14 = r15
        L_0x004b:
            r0 = r1 & 1024(0x400, float:1.435E-42)
            if (r0 == 0) goto L_0x0055
        L_0x004f:
            r1 = r16
            r1.<init>(r2, r3, r5, r6, r8, r9, r11, r12, r13, r14, r15)
            return
        L_0x0055:
            r15 = r30
            goto L_0x004f
        L_0x0058:
            r9 = r24
            goto L_0x0037
        */
        throw new UnsupportedOperationException("Method not decompiled: com.p2082ss.android.ugc.aweme.feed.model.CaptionItemModel.<init>(java.lang.String, long, java.lang.String, long, java.lang.String, long, boolean, int, java.lang.String, java.lang.String, java.lang.String, int, h.f.b.g):void");
    }
}
