package com.p2082ss.android.ugc.aweme.feed.p2979x;

import com.bytedance.covode.number.Covode;
import com.p2082ss.android.ugc.aweme.feed.model.Audio;
import com.p2082ss.android.ugc.aweme.feed.model.Aweme;
import com.p2082ss.android.ugc.aweme.feed.model.CaptionItemModel;
import com.p2082ss.android.ugc.aweme.feed.model.CaptionLanguage;
import com.p2082ss.android.ugc.aweme.feed.model.CaptionModel;
import com.p2082ss.android.ugc.aweme.feed.model.TtsInfos;
import com.p2082ss.android.ugc.aweme.feed.model.Video;
import com.p2082ss.android.ugc.aweme.sticker.data.C75309d;
import com.p2082ss.android.ugc.aweme.sticker.data.EnumC75306a;
import com.p2082ss.android.ugc.trill.setting.TranslatedCaptionCacheServiceImpl;
import java.util.List;
import p4600h.p4601a.C89070n;
import p4600h.p4611f.p4613b.C89219l;

/* renamed from: com.ss.android.ugc.aweme.feed.x.ah */
public final class C50532ah {

    /* renamed from: a */
    public static final C50532ah f116799a = new C50532ah();

    private C50532ah() {
    }

    static {
        Covode.recordClassIndex(59679);
    }

    /* renamed from: h */
    public static int m94732h(Aweme aweme) {
        if (m94734j(aweme)) {
            return 0;
        }
        return 1;
    }

    /* renamed from: i */
    public static int m94733i(Aweme aweme) {
        if (m94735k(aweme)) {
            return 0;
        }
        return 1;
    }

    /* renamed from: j */
    public static boolean m94734j(Aweme aweme) {
        Video video;
        CaptionModel captionModel;
        List<CaptionItemModel> captionList;
        if (aweme == null || (video = aweme.getVideo()) == null || (captionModel = video.getCaptionModel()) == null || (captionList = captionModel.getCaptionList()) == null || captionList.isEmpty()) {
            return false;
        }
        return true;
    }

    /* renamed from: k */
    public static boolean m94735k(Aweme aweme) {
        Audio audio;
        List<TtsInfos> ttsInfos;
        if (aweme == null || (audio = aweme.getAudio()) == null || (ttsInfos = audio.getTtsInfos()) == null || C89070n.m154579f((List) ttsInfos) == null) {
            return false;
        }
        return true;
    }

    /* renamed from: c */
    public static String m94727c(Aweme aweme) {
        Video video;
        CaptionModel captionModel;
        List<CaptionItemModel> captionList;
        Long l;
        CaptionModel captionModel2;
        CaptionLanguage originalCaptionLanguage;
        if (aweme == null || (video = aweme.getVideo()) == null || (captionModel = video.getCaptionModel()) == null || (captionList = captionModel.getCaptionList()) == null || captionList.isEmpty()) {
            return "";
        }
        Video video2 = aweme.getVideo();
        if (video2 == null || (captionModel2 = video2.getCaptionModel()) == null || (originalCaptionLanguage = captionModel2.getOriginalCaptionLanguage()) == null) {
            l = null;
        } else {
            l = Long.valueOf(originalCaptionLanguage.getLanguageId());
        }
        for (T t : captionList) {
            long languageId = t.getLanguageId();
            if (l != null && languageId == l.longValue()) {
                if (t.isAutoGenerated()) {
                    return "asr";
                }
                return "creator";
            }
        }
        return "";
    }

    /* JADX WARNING: Removed duplicated region for block: B:25:0x0054  */
    /* renamed from: e */
    /* Code decompiled incorrectly, please refer to instructions dump. */
    public static java.lang.String m94729e(com.p2082ss.android.ugc.aweme.feed.model.Aweme r9) {
        /*
        // Method dump skipped, instructions count: 113
        */
        throw new UnsupportedOperationException("Method not decompiled: com.p2082ss.android.ugc.aweme.feed.p2979x.C50532ah.m94729e(com.ss.android.ugc.aweme.feed.model.Aweme):java.lang.String");
    }

    /* JADX WARNING: Code restructure failed: missing block: B:14:0x0026, code lost:
        if (r0 == null) goto L_0x0028;
     */
    /* renamed from: f */
    /* Code decompiled incorrectly, please refer to instructions dump. */
    public static boolean m94730f(com.p2082ss.android.ugc.aweme.feed.model.Aweme r3) {
        /*
            r1 = 0
            if (r3 == 0) goto L_0x0051
            com.ss.android.ugc.aweme.feed.model.Video r0 = r3.getVideo()
            if (r0 == 0) goto L_0x0051
            com.ss.android.ugc.aweme.feed.model.CaptionModel r0 = r0.getCaptionModel()
            if (r0 == 0) goto L_0x0051
            java.util.List r0 = r0.getCaptionList()
        L_0x0013:
            r2 = 0
            if (r0 == 0) goto L_0x0031
            com.ss.android.ugc.aweme.feed.model.Video r0 = r3.getVideo()
            if (r0 == 0) goto L_0x004f
            com.ss.android.ugc.aweme.feed.model.CaptionModel r0 = r0.getCaptionModel()
            if (r0 == 0) goto L_0x004f
            java.util.List r0 = r0.getCaptionList()
            if (r0 != 0) goto L_0x002b
        L_0x0028:
            p4600h.p4611f.p4613b.C89219l.m154715b()
        L_0x002b:
            boolean r0 = r0.isEmpty()
            if (r0 == 0) goto L_0x0032
        L_0x0031:
            return r2
        L_0x0032:
            com.ss.android.ugc.aweme.feed.model.Video r0 = r3.getVideo()
            if (r0 == 0) goto L_0x0044
            com.ss.android.ugc.aweme.feed.model.CaptionModel r0 = r0.getCaptionModel()
            if (r0 == 0) goto L_0x0044
            java.util.List r1 = r0.getCaptionList()
            if (r1 != 0) goto L_0x0047
        L_0x0044:
            p4600h.p4611f.p4613b.C89219l.m154715b()
        L_0x0047:
            int r1 = r1.size()
            r0 = 1
            if (r1 <= r0) goto L_0x0031
            return r0
        L_0x004f:
            r0 = r1
            goto L_0x0028
        L_0x0051:
            r0 = r1
            goto L_0x0013
        */
        throw new UnsupportedOperationException("Method not decompiled: com.p2082ss.android.ugc.aweme.feed.p2979x.C50532ah.m94730f(com.ss.android.ugc.aweme.feed.model.Aweme):boolean");
    }

    /* renamed from: g */
    public static boolean m94731g(Aweme aweme) {
        Video video;
        CaptionModel captionModel;
        List<CaptionItemModel> captionList;
        Long l;
        C75309d e;
        CaptionModel captionModel2;
        CaptionLanguage originalCaptionLanguage;
        if (aweme == null || (video = aweme.getVideo()) == null || (captionModel = video.getCaptionModel()) == null || (captionList = captionModel.getCaptionList()) == null || captionList.isEmpty()) {
            return false;
        }
        Video video2 = aweme.getVideo();
        if (video2 == null || (captionModel2 = video2.getCaptionModel()) == null || (originalCaptionLanguage = captionModel2.getOriginalCaptionLanguage()) == null) {
            l = null;
        } else {
            l = Long.valueOf(originalCaptionLanguage.getLanguageId());
        }
        for (T t : captionList) {
            long languageId = t.getLanguageId();
            if (l != null && languageId == l.longValue() && !t.isAutoGenerated() && (e = C50539g.m94751e(aweme)) != null && e.getLocation() == EnumC75306a.LEFT_TOP.getValue()) {
                return true;
            }
        }
        return false;
    }

    /* JADX WARNING: Code restructure failed: missing block: B:14:0x0026, code lost:
        if (r0 == null) goto L_0x0028;
     */
    /* JADX WARNING: Code restructure failed: missing block: B:40:0x008b, code lost:
        if (r0 == null) goto L_0x008d;
     */
    /* renamed from: a */
    /* Code decompiled incorrectly, please refer to instructions dump. */
    public static boolean m94725a(com.p2082ss.android.ugc.aweme.feed.model.Aweme r7) {
        /*
        // Method dump skipped, instructions count: 223
        */
        throw new UnsupportedOperationException("Method not decompiled: com.p2082ss.android.ugc.aweme.feed.p2979x.C50532ah.m94725a(com.ss.android.ugc.aweme.feed.model.Aweme):boolean");
    }

    /* JADX WARNING: Code restructure failed: missing block: B:14:0x0026, code lost:
        if (r0 == null) goto L_0x0028;
     */
    /* JADX WARNING: Code restructure failed: missing block: B:24:0x0042, code lost:
        if (r0 == null) goto L_0x0044;
     */
    /* renamed from: b */
    /* Code decompiled incorrectly, please refer to instructions dump. */
    public static boolean m94726b(com.p2082ss.android.ugc.aweme.feed.model.Aweme r7) {
        /*
        // Method dump skipped, instructions count: 157
        */
        throw new UnsupportedOperationException("Method not decompiled: com.p2082ss.android.ugc.aweme.feed.p2979x.C50532ah.m94726b(com.ss.android.ugc.aweme.feed.model.Aweme):boolean");
    }

    /* renamed from: d */
    public static long m94728d(Aweme aweme) {
        Video video;
        CaptionModel captionModel;
        List<CaptionItemModel> captionList;
        CaptionModel captionModel2;
        CaptionLanguage originalCaptionLanguage;
        Long l = null;
        boolean a = C89219l.m154714a((Object) TranslatedCaptionCacheServiceImpl.m146355j().mo108891c(), (Object) (aweme != null ? aweme.getAid() : null));
        if (aweme == null || (video = aweme.getVideo()) == null || (captionModel = video.getCaptionModel()) == null || (captionList = captionModel.getCaptionList()) == null || captionList.isEmpty()) {
            return 0;
        }
        Video video2 = aweme.getVideo();
        if (!(video2 == null || (captionModel2 = video2.getCaptionModel()) == null || (originalCaptionLanguage = captionModel2.getOriginalCaptionLanguage()) == null)) {
            l = Long.valueOf(originalCaptionLanguage.getLanguageId());
        }
        for (T t : captionList) {
            if (a) {
                long languageId = t.getLanguageId();
                if (l != null && languageId == l.longValue()) {
                }
            } else {
                long languageId2 = t.getLanguageId();
                if (l != null && languageId2 == l.longValue()) {
                }
            }
            return t.getComplaintId();
        }
        return 0;
    }

    /* renamed from: a */
    public static int m94724a(boolean z, Aweme aweme) {
        Video video;
        CaptionModel captionModel;
        List<CaptionItemModel> captionList;
        Long l;
        CaptionModel captionModel2;
        CaptionLanguage originalCaptionLanguage;
        if (aweme == null || (video = aweme.getVideo()) == null || (captionModel = video.getCaptionModel()) == null || (captionList = captionModel.getCaptionList()) == null || captionList.isEmpty()) {
            return 0;
        }
        Video video2 = aweme.getVideo();
        if (video2 == null || (captionModel2 = video2.getCaptionModel()) == null || (originalCaptionLanguage = captionModel2.getOriginalCaptionLanguage()) == null) {
            l = null;
        } else {
            l = Long.valueOf(originalCaptionLanguage.getLanguageId());
        }
        for (T t : captionList) {
            long languageId = t.getLanguageId();
            if (l == null || languageId != l.longValue() || !z) {
                long languageId2 = t.getLanguageId();
                if ((l != null && languageId2 == l.longValue()) || z) {
                }
            }
            try {
                return Integer.parseInt(t.getVersionType());
            } catch (Exception unused) {
            }
        }
        return 0;
    }
}
