package com.google.android.gms.common.api.internal;

import com.bytedance.covode.number.Covode;
import com.google.android.gms.common.api.AbstractC25478k;
import com.google.android.gms.common.api.AbstractC25485p;
import com.google.android.gms.common.api.AbstractC25486q;
import com.google.android.gms.common.api.Status;
import java.util.concurrent.TimeUnit;

/* renamed from: com.google.android.gms.common.api.internal.bp */
public final class C25406bp<R extends AbstractC25485p> extends AbstractC25478k<R> {

    /* renamed from: a */
    public final Status f60280a;

    static {
        Covode.recordClassIndex(30805);
    }

    @Override // com.google.android.gms.common.api.AbstractC25478k
    /* renamed from: b */
    public final boolean mo41544b() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // com.google.android.gms.common.api.AbstractC25478k
    /* renamed from: c */
    public final Integer mo41545c() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // com.google.android.gms.common.api.AbstractC25478k
    /* renamed from: a */
    public final void mo41539a() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // com.google.android.gms.common.api.AbstractC25478k
    /* renamed from: a */
    public final R mo41538a(TimeUnit timeUnit) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // com.google.android.gms.common.api.AbstractC25478k
    /* renamed from: a */
    public final void mo41541a(AbstractC25478k.AbstractC25479a aVar) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // com.google.android.gms.common.api.AbstractC25478k
    /* renamed from: a */
    public final void mo41543a(AbstractC25486q<? super R> qVar) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }
}
